### ISSUE TITLE
Class Illuminate\Log\Logger does not exist

### ISSUE THREAD

**Issue by kwarcu** [geocoder-php/GeocoderLaravel#166]
### General Information
GeocoderLaravel Version: 4.2.2
Laravel Version: 5.4
PHP Version: 7.2
Operating System and Version: MacOS/AWS Linux

### Issue Description
Getting `Class Illuminate\Log\Logger does not exist` fatal error. Issue appeared after updating lib from 4.2.0 to 4.2.2 and I suppose it is caused by this change: https://github.com/geocoder-php/GeocoderLaravel/compare/4.2.0..4.2.2#diff-142758f8527fa721a30a4f1cc61ff755R21

### Steps to Replicate
Try to use geocoder

### Stack Trace
```
ReflectionException: Class Illuminate\Log\Logger does not exist
#109 /vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass::__construct
#108 /vendor/laravel/framework/src/Illuminate/Container/Container.php(729): Illuminate\Container\Container::build
#107 /vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container::resolve
#106 /vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container::make
#105 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Foundation\Application::make
#104 /vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(106): app
#103 /vendor/toin0u/geocoder-laravel/src/ProviderAndDumperAggregator.php(255): Geocoder\Laravel\ProviderAndDumperAggregator::Geocoder\Laravel\{closure}
#102 [internal](0): array_map
#101 /vendor/laravel/framework/src/Illuminate/Support/Collection.php(766): Illuminate\Support\Collection::map
#100 /vendor/toin0u/geocoder-laravel/src/ProviderAndDumperAggregator.php(264): Geocoder\Laravel\ProviderAndDumperAggregator::getProvidersFromConfiguration
#99 /vendor/toin0u/geocoder-laravel/src/ProviderAndDumperAggregator.php(154): Geocoder\Laravel\ProviderAndDumperAggregator::registerProvidersFromConfig
#98 /vendor/toin0u/geocoder-laravel/src/Providers/GeocoderService.php(35): Geocoder\Laravel\Providers\GeocoderService::Geocoder\Laravel\Providers\{closure}
#97 /vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Illuminate\Container\Container::build
#96 /vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container::resolve
#95 /vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\Container::makeWith
#94 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Foundation\Application::makeWith
#93 /vendor/laravel/framework/src/Illuminate/Container/Container.php(248): Illuminate\Container\Container::Illuminate\Container\{closure}
#92 /vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Illuminate\Container\Container::build
#91 /vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container::resolve
#90 /vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container::make
#89 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Foundation\Application::make
#88 /vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(106): app
#87 /app/Domain/Core/GeocodeService.php(21): App\Domain\Core\GeocodeService::__construct
#86 /app/Domain/Client/Details/ContactInfoManager.php(73): App\Domain\Client\Details\ContactInfoManager::geocode
#85 /app/Domain/Client/Details/ContactInfoManager.php(64): App\Domain\Client\Details\ContactInfoManager::updatePlace
#84 /app/Http/Controllers/Client/DomainController.php(379): App\Http\Controllers\Client\DomainController::update
#83 [internal](0): call_user_func_array
#82 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): Illuminate\Routing\Controller::callAction
#81 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\ControllerDispatcher::dispatch
#80 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\Route::runController
#79 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route::run
#78 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Router::Illuminate\Routing\{closure}
#77 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#76 /app/Http/Middleware/Client/VerifyClientOwnership.php(142): App\Http\Middleware\Client\VerifyClientOwnership::handle
#75 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#74 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#73 /app/Http/Middleware/Client/VerifyClientPermission.php(64): App\Http\Middleware\Client\VerifyClientPermission::handle
#72 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#71 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#70 /app/Http/Controllers/Client/ClientBaseController.php(50): App\Http\Controllers\Client\ClientBaseController::App\Http\Controllers\Client\{closure}
#69 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#68 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#67 /app/Http/Middleware/Client/Authenticate.php(84): App\Http\Middleware\Client\Authenticate::handle
#66 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#65 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#64 /app/Http/Middleware/Common/UtmCampaign.php(74): App\Http\Middleware\Common\UtmCampaign::handle
#63 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#62 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#61 /app/Http/Middleware/Client/VerifySubdomain.php(46): App\Http\Middleware\Client\VerifySubdomain::handle
#60 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#59 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#58 /core/Sentry/Middleware/SentryContext.php(81): Core\Sentry\Middleware\SentryContext::handle
#57 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#56 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#55 /app/Http/Middleware/Client/CreateFreshApiToken.php(27): App\Http\Middleware\Client\CreateFreshApiToken::handle
#54 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#53 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#52 /app/Http/Middleware/Common/SubstituteBindings.php(45): App\Http\Middleware\Common\SubstituteBindings::handle
#51 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#50 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#49 /app/Http/Middleware/Common/Country.php(54): App\Http\Middleware\Common\Country::handle
#48 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#47 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#46 /app/Http/Middleware/Common/Locale.php(59): App\Http\Middleware\Common\Locale::handle
#45 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#44 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#43 /app/Http/Middleware/Common/Timezone.php(44): App\Http\Middleware\Common\Timezone::handle
#42 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#41 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#40 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
#39 /app/Http/Middleware/VerifyCsrfToken.php(40): App\Http\Middleware\VerifyCsrfToken::handle
#38 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#37 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#36 /app/Http/Middleware/Common/DomainRedirect.php(46): App\Http\Middleware\Common\DomainRedirect::handle
#35 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#34 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#33 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\View\Middleware\ShareErrorsFromSession::handle
#32 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#31 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#30 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession::handle
#29 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#28 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#27 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
#26 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#25 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#24 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Cookie\Middleware\EncryptCookies::handle
#23 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#22 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#21 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline::then
#20 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Routing\Router::runRouteWithinStack
#19 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router::dispatchToRoute
#18 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router::dispatch
#17 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
#16 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#15 /app/Http/Middleware/ChangeSessionDriver.php(23): App\Http\Middleware\ChangeSessionDriver::handle
#14 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#13 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#12 /vendor/fideloper/proxy/src/TrustProxies.php(56): Fideloper\Proxy\TrustProxies::handle
#11 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#10 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#9 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::handle
#8 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#7 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#6 /vendor/barryvdh/laravel-cors/src/HandlePreflight.php(35): Barryvdh\Cors\HandlePreflight::handle
#5 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#4 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#3 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline::then
#2 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel::handle
#0 /public/index.php(61): null
```

**Comment by mikebronner** [comment]
@kwarcu Sorry for taking so long to respond. I am not seeing this error, and am assuming it has since been resolved.
